### PR TITLE
Remove indentations in code block on INSTALL.md

### PR DESCRIPTION
**Pull request by mingrammer**

### CODE REVIEW

**Comment by danielshahaf** [comment]
What's the purpose of this? Does this affect rendering in any way?

**Comment by mingrammer** [comment]
Yes, it does.

Before:

screenshot 2018-10-07 23 31 22

After:

screenshot 2018-10-07 23 31 37

After is cleaner than before.

**Comment by danielshahaf** [comment]
Thanks. Merged in cf88b63523e8 with a changed log message (primarily added a "foo:" prefix per convention).

**Comment by mingrammer** [comment]
Thanks :)

**Pull request closed without merging**
