### PR TITLE
main: Highlight path after globbing checks

### LINKED ISSUE #468: path wrongly precedes globbing
```zsh
% touch \*
% echo *
```

The `*` is highlighted as `path`, it should be highlighted as `globbing`.

Bisected to dc1b2f6fa4bb477e7b9712ebdb4e82beb50258c6.

### PR DESCRIPTION
**Pull request by phy1729**
Closes #468.

### CODE REVIEW

**Comment by danielshahaf** [comment]
This doesn't fix #468: https://github.com/zsh-users/zsh-syntax-highlighting/commit/ff61a496b5ea5f17eb0621314edb09219d421e44 still fails.  Interactively I see that it's now fg=blue,underline, compared to fg=default,underline in current master and fg=blue (no underline) before dc1b2f6fa4bb477e7b9712ebdb4e82beb50258c6.

Do we agree that _this specific case_ should be highlighted as it had been prior to dc1b2f6fa4bb477e7b9712ebdb4e82beb50258c6?

**Comment by phy1729** [comment]
Ah I didn't know you had added a test and I failed to see the blue underline on a black background when testing interactively before. Fixed now.

**Comment by danielshahaf** [comment]
Thanks. The new code looks good. Could you add a regression test for `noglob echo *` being highlighted as a path?

Also, `'f'oo` (which was discussed on #468) is now actually highlighted as `'f'` yellow+underline and `oo` default color + underline.  Would it be possible for you to add a test for that as well?  The zle internal combining logic might change in future zsh releases.

**Comment by danielshahaf** [comment]
For posterity: while reviewing this I found #474.

**Comment by phy1729** [comment]
> Also, 'f'oo (which was discussed on #468) is now actually highlighted as 'f' yellow+underline and oo default color + underline. Would it be possible for you to add a test for that as well? The zle internal combining logic might change in future zsh releases.

At present, no. The test harness only sees the `path` style for the whole of `'f'oo`. Some changes would need to be made to the test harness and API to specify multiple styles for a single `expected_region_highlight` element. Testing the merging happens as expected would be another issue on top.

**Comment by danielshahaf** [comment]
Thanks. I think it's a behaviour we'd like to keep so I'll file a milestone=blue-sky issue about. Thanks for the merge. Excuse brevity.

**Comment by danielshahaf** [comment]
> Thanks. I think it's a behaviour we'd like to keep so I'll file a milestone=blue-sky issue about. Thanks for the merge. Excuse brevity.

Filed #475.

**Pull request closed without merging**
